print("Please enter the following information so i can sell it for a profit ")
a=input("First name:")
b=input("last name:")
c=input("Grade(9-12):")
d=input("student-ID:")
e=input("Login:")
f=input("GPA[0.0-o.4]:")
print("\nyour information:")
print("\tlogin:",e)
print("\t ID:",d)
print("\t Name:",a+b)
print("\t GPI:",f)
print("\t Grade:",c)